### ISSUE TITLE
How to re-render same children with a prop change?

### ISSUE THREAD

**Issue by vapaternina** [gkaemmer/react-fade-in#10]
I have a FadeIn implementation but only appear when its firstly render, how to do I for re render when a prop change? 

I am loading images and change the render component between <Skeleton/> (MaterialUI) and <img/>

**Comment by gkaemmer** [comment]
Do you want to re-render the whole animation (all children animating in), or just animate the addition/removal of a single child element?

If it's the former, you can update a `key` prop to the `FadeIn` component and React will re-mount a new version of the component:
```js
<FadeIn key="1">...</FadeIn>
// FadeIn animation happens on mount
// Then, in a later render
<FadeIn key="2" delay={200}>...</FadeIn>
// Full animation happens again with different properties
```

**Comment by vapaternina** [comment]
I get it, thanks a lot.
