### ISSUE TITLE
Fade Out?

### ISSUE THREAD

**Issue by wtesler** [gkaemmer/react-fade-in#14]
Any way to play it backwards and then unmount inner components?

**Comment by RyanPaiva56** [comment]
This would be great :+1:

**Comment by gkaemmer** [comment]
Hey, sorry for the long response time! Doing this in a very robust way would be out of the scope of this library, but version 2.0.0 adds the `visible` prop which you can use to play the animation in reverse (set `visible={false}` when you want the children to fade out).

If you want removed children to "stick around" after you've removed them to give them time to animate out, I recommend you check out [`react-transition-group`](https://github.com/reactjs/react-transition-group) -- it's a perfect library for that type of thing.

Marking this as closed for now.
