### ISSUE TITLE
Having an element with position fixed does not work 

### ISSUE THREAD

**Issue by atnpcg** [gkaemmer/react-fade-in#16]
the library uses transform: translateY(nn); to make the effect in the parent element, 
however if a child tries to use position: fixed, the element won't be in a fixed position.
example:
https://jsfiddle.net/nd68kpcu/

we should clean the inline css of `translateY` once the transition is complete

**Comment by gkaemmer** [comment]
Oh that's an interesting bug, I didn't know about that CSS quirk. Removing the `transform` CSS rule after the transition is complete could fix this, but if a fixed child element is mounted when the animation starts, I think the fixed element will "jump out" of the parent once the `transform` rule is removed.

Just something to be aware of--I think you're right though that it's a good idea to clean up the `transform: translateY(0)` rule once the transition is done.

**Comment by gkaemmer** [comment]
Closed by #17
