### ISSUE TITLE
Importing into a TS project provides a module declaration warning

### ISSUE THREAD

**Issue by RyanPaiva56** [gkaemmer/react-fade-in#18]
> TS7016: Could not find a declaration file for module 'react-fade-in'. '/home/ryan/Code/llapp10/node_modules/react-fade-in/lib/index.js' implicitly has an 'any' type.   Try `npm i --save-dev @types/react-fade-in` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-fade-in';`

**Comment by gkaemmer** [comment]
Hmm you're totally right on this one -- I should add typings in the next release. Thanks for the report!

**Comment by gkaemmer** [comment]
Typings are added in 2.0.0 (see: #19)
