### ISSUE TITLE
Is there a way to fade-in when component is seen on screen?

### ISSUE THREAD

**Issue by TendezaDev** [gkaemmer/react-fade-in#23]

**Comment by gkaemmer** [comment]
Can you say more? Might the `visible` prop work for this purpose?

**Comment by TendezaDev** [comment]
What I mean is I want, for example, some text to fade in when a user scrolls over the text. I tried using visible, but I couldn't get it to work. Is that what `visible` is for?

**Comment by gkaemmer** [comment]
Ah, I see. This library doesn't have built-in support for scroll listening, but you could combine the `visible` prop with something like [react-visibility-sensor](https://www.npmjs.com/package/react-visibility-sensor):

```js
import VisibilitySensor from "react-visibility-sensor";
import FadeIn from "react-fade-in";

function MyComponent() {
  return (
    <div>
      ...
      <VisibilitySensor>
        {({isVisible}) =>
          <FadeIn visible={isVisible}>
            ... your content to fade in here ...
          </FadeIn>
        }
      </VisibilitySensor>
    </div>
  );
}
```

**Comment by TendezaDev** [comment]
@gkaemmer Aah thank you!
