### ISSUE TITLE
Switch to animating translateY instead of top

### ISSUE THREAD

**Issue by bogdansoare** [gkaemmer/react-fade-in#8]
[Animating the `top` property](https://github.com/gkaemmer/react-fade-in/blob/master/src/FadeIn.js#L45) will have some performance impacts, basically animating `top` will trigger the browser to [perform layout operations](https://csstriggers.com/top). 
Instead use `transform` with `translateY` so the operation can likely be [carried out by the compositor thread](https://csstriggers.com/transform) with the help of the GPU.

**Comment by gkaemmer** [comment]
This is a good idea! Will do in the next few days

**Comment by gkaemmer** [comment]
Published in v1.0.0. I made this a major version bump because removing `position: relative` might break some people's layouts. It's a pretty easy fix (using `childClassName`) to add `position: relative` back onto the child elements.

**Comment by bogdansoare** [comment]
Awesome, keep up the good work with the library 👍
